name: tmdb_infrastructure
description: TMDB infrastructure library
version: 1.0.0
authors:
- Denis Feoktistov <nonameden@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  built_collection: ^4.0.0
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.0
  test: ^1.0.0